services:
  - type: web
    name: rfp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: VALUESERP_API_KEY
        sync: false
      - key: THOT_API_KEY
        sync: false
      - key: VECTOR_STORE_TYPE
        value: faiss
      - key: VECTOR_STORE_MODEL
        value: all-MiniLM-L6-v2
      - key: EMBEDDING_TYPE
        value: openai
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
